insert into users (rating, likes) values (78, 'cat');
insert into users (rating, likes) values (37, 'small');
insert into users (rating, likes) values (14, 'russian blue');
insert into users (rating, likes) values (52, 'russian blue');
insert into users (rating, likes) values (56, 'dog');
insert into users (rating, likes) values (9, 'dog');
insert into users (rating, likes) values (56, 'small');
insert into users (rating, likes) values (5, 'cat');
insert into users (rating, likes) values (4, 'obedient');
insert into users (rating, likes) values (71, 'persian cat');
insert into users (rating, likes) values (73, 'russian blue');
insert into users (rating, likes) values (78, 'small');
insert into users (rating, likes) values (65, 'obedient');
insert into users (rating, likes) values (33, 'obedient');
insert into users (rating, likes) values (50, 'golden retriever');
insert into users (rating, likes) values (50, 'russian blue');
insert into users (rating, likes) values (54, 'russian blue');
insert into users (rating, likes) values (65, 'golden retriever');
insert into users (rating, likes) values (92, 'golden retriever');
insert into users (rating, likes) values (19, 'small');
insert into users (rating, likes) values (41, 'golden retriever');
insert into users (rating, likes) values (2, 'dog');
insert into users (rating, likes) values (94, 'dog');
insert into users (rating, likes) values (42, 'persian cat');
insert into users (rating, likes) values (17, 'dog');
insert into users (rating, likes) values (58, 'bulldog');
insert into users (rating, likes) values (27, 'russian blue');
insert into users (rating, likes) values (74, 'obedient');
insert into users (rating, likes) values (39, 'dog');
insert into users (rating, likes) values (38, 'persian cat');
insert into users (rating, likes) values (18, 'bulldog');
insert into users (rating, likes) values (66, 'cat');
insert into users (rating, likes) values (68, 'bulldog');
insert into users (rating, likes) values (56, 'persian cat');
insert into users (rating, likes) values (75, 'cat');
insert into users (rating, likes) values (45, 'bulldog');
insert into users (rating, likes) values (77, 'russian blue');
insert into users (rating, likes) values (100, 'persian cat');
insert into users (rating, likes) values (30, 'small');
insert into users (rating, likes) values (65, 'bulldog');
insert into users (rating, likes) values (79, 'persian cat');
insert into users (rating, likes) values (41, 'persian cat');
insert into users (rating, likes) values (70, 'golden retriever');
insert into users (rating, likes) values (35, 'russian blue');
insert into users (rating, likes) values (31, 'golden retriever');
insert into users (rating, likes) values (57, 'dog');
insert into users (rating, likes) values (47, 'persian cat');
insert into users (rating, likes) values (32, 'bulldog');
insert into users (rating, likes) values (54, 'obedient');
insert into users (rating, likes) values (86, 'bulldog');
insert into users (rating, likes) values (75, 'russian blue');
insert into users (rating, likes) values (41, 'bulldog');
insert into users (rating, likes) values (45, 'golden retriever');
insert into users (rating, likes) values (8, 'bulldog');
insert into users (rating, likes) values (10, 'cat');
insert into users (rating, likes) values (82, 'cat');
insert into users (rating, likes) values (47, 'golden retriever');
insert into users (rating, likes) values (41, 'bulldog');
insert into users (rating, likes) values (5, 'cat');
insert into users (rating, likes) values (33, 'golden retriever');
insert into users (rating, likes) values (46, 'golden retriever');
insert into users (rating, likes) values (46, 'golden retriever');
insert into users (rating, likes) values (75, 'bulldog');
insert into users (rating, likes) values (24, 'golden retriever');
insert into users (rating, likes) values (0, 'dog');
insert into users (rating, likes) values (61, 'obedient');
insert into users (rating, likes) values (84, 'small');
insert into users (rating, likes) values (74, 'dog');
insert into users (rating, likes) values (43, 'golden retriever');
insert into users (rating, likes) values (17, 'bulldog');
insert into users (rating, likes) values (60, 'bulldog');
insert into users (rating, likes) values (43, 'cat');
insert into users (rating, likes) values (65, 'russian blue');
insert into users (rating, likes) values (2, 'cat');
insert into users (rating, likes) values (52, 'cat');
insert into users (rating, likes) values (91, 'persian cat');
insert into users (rating, likes) values (20, 'obedient');
insert into users (rating, likes) values (38, 'golden retriever');
insert into users (rating, likes) values (82, 'small');
insert into users (rating, likes) values (48, 'cat');
insert into users (rating, likes) values (91, 'cat');
insert into users (rating, likes) values (88, 'russian blue');
insert into users (rating, likes) values (52, 'russian blue');
insert into users (rating, likes) values (64, 'bulldog');
insert into users (rating, likes) values (73, 'persian cat');
insert into users (rating, likes) values (46, 'bulldog');
insert into users (rating, likes) values (6, 'cat');
insert into users (rating, likes) values (33, 'russian blue');
insert into users (rating, likes) values (6, 'obedient');
insert into users (rating, likes) values (85, 'obedient');
insert into users (rating, likes) values (27, 'obedient');
insert into users (rating, likes) values (71, 'small');
insert into users (rating, likes) values (67, 'golden retriever');
insert into users (rating, likes) values (2, 'dog');
insert into users (rating, likes) values (33, 'small');
insert into users (rating, likes) values (70, 'obedient');
insert into users (rating, likes) values (24, 'persian cat');
insert into users (rating, likes) values (14, 'small');
insert into users (rating, likes) values (91, 'bulldog');
insert into users (rating, likes) values (17, 'bulldog');
